AccentList = {
    "British": "co.uk",
    "American": "com",
    "Australian": "com.au",
    "Irish": "ie",
    "Argentinean": "com.ar",
    "Spanish": "es",
    "Mexican": "com.mx",
    "Canadian": "ca",
    "Brazilian": "com.br",
    "Italian": "it",
    "French": "fr",
    "Indian": "co.in",
    "Icelandic": "is",
    "Hebrew": "co.il",
    "Latin": "la",
    "Japanese": "co.jp",
    "Korean": "co.kr",
    "Thai": "co.th",
    "Filipino": "tl",
    "Vietnamese": "co.vi",
    "Arabic": "az",
    "German": "dm",
    "Estonian": "et",
    "Finnish": "fi",
    "Hungarian": "hu",
    "Dutch": "nl",
    "Norwegian": "no",
    "Polish": "pl",
    "Portuguese": "pt",
    "Romanian": "ro",
    "Russian": "ru",
    "Swedish": "com.sv",
    "South African": "co.za",    
}


