language_dict = {
 'Spanish (El Salvador)-Lorena- (Female)': 'English-F',
 'Spanish (Venezuela)-Sebastian- (Male)': 'English-M',
 'Spanish (El Salvador)-Lorena- (Female)': 'English-F',
 'Spanish (Venezuela)-Sebastian- (Male)': 'English-M',
 'Korean-Sun-Hi- (Female)': 'Korean-F',
 'Korean-InJoon- (Male)': 'Korean-M',
 'Thai-Premwadee- (Female)': 'Thai-F',
 'Thai-Niwat- (Male)': 'Thai-M',
 'Vietnamese-HoaiMy- (Female)': 'Vietnamese-F',
 'Vietnamese-NamMinh- (Male)': 'Vietnamese-M',
 'Japanese-Nanami- (Female)':'Japanese-F',
 'Japanese-Keita- (Male)': 'Japanese-M',
 'French-Denise- (Female)': 'French-F',
 'French-Henri- (Male)': 'French-M',
 'Brazilian-Francisca- (Female)': 'Brazilian-F', 
 'Brazilian-Antonio- (Male)': 'Brazilian-M',
 'Brazilian-Francisca- (Female)': 'Portuguese-F', 
 'Brazilian-Antonio- (Male)': 'Portuguese-M',
 'Hebrew-Hila- (Female)': 'Hebrew-F',
 'Hebrew-Avri- (Male)': 'Hebrew-M',
 'Italian-Isabella- (Female)': 'Italian-F',
 'Italian-Diego- (Male)': 'Italian-M',
 'Dutch-Colette- (Female)': 'Dutch-F',
 'Dutch-Maarten- (Male)': 'Dutch-M',
 'Norwegian-Pernille- (Female)': 'Norwegian-F',
 'Norwegian-Finn- (Male)': 'Norwegian-M',
 'Swedish-Sofie- (Female)': 'Swedish-F',
 'Swedish-Mattias- (Male)': 'Swedish-M',
 'Arabic-Zariyah- (Female)': 'Arabic-F',
 'Arabic-Hamed- (Male)': 'Arabic-M',
 'Greek-Athina- (Female)': 'Greek-F',
 'Greek-Nestoras- (Male)':'Greek-M',
 'German-Amala- (Female)': 'German-F',
 'German-Conrad- (Male)': 'German-M',
 'Danish (Denmark)-Christel- (Female)': 'Danish-F',
 'Danish (Denmark)-Jeppe- (Male)': 'Danish-M',
 'Estonian (Estonia)-Anu- (Female)': 'Estonian-F',
 'Estonian (Estonia)-Kert- (Male)': 'Estonian-M',
 'Persian (Iran)-Dilara- (Female)': 'Persian-F',
 'Persian (Iran)-Farid- (Male)': 'Persian-M',
 'Finnish (Finland)-Noora- (Female)': 'Finnish-F',
 'Finnish (Finland)-Harri- (Male)': 'Finnish-M',
}