language_dict = {
 'English-F': 'es-VE-SebastianNeural',
 'English-M': 'es-VE-SebastianNeural',
 'Spanish-F': 'es-VE-SebastianNeural',
 'Spanish-M': 'es-VE-SebastianNeural',
 'Korean-F': 'Korean-Sun-Hi- (Female)',
 'Korean-M': 'Korean-InJoon- (Male)',
 'Thai-F': 'Thai-Premwadee- (Female)',
 'Thai-M': 'Thai-Niwat- (Male)',
 'Vietnamese-F': 'Vietnamese-HoaiMy- (Female)',
 'Vietnamese-M': 'Vietnamese-NamMinh- (Male)',
 'Japanese-F': 'Japanese-Nanami- (Female)',
 'Japanese-M': 'Japanese-Keita- (Male)',
 'French-F': 'French-Denise- (Female)',
 'French-M': 'French-Henri- (Male)',
 'Brazilian-F': 'Brazilian-Francisca- (Female)', 
 'Brazilian-M': 'Brazilian-Antonio- (Male)',
 'Portuguese-F': 'Brazilian-Francisca- (Female)', 
 'Portuguese-M': 'Brazilian-Antonio- (Male)',
 'Hebrew-F': 'Hebrew-Hila- (Female)',
 'Hebrew-M': 'Hebrew-Avri- (Male)',
 'Italian-F': 'Italian-Isabella- (Female)',
 'Italian-M': 'Italian-Diego- (Male)',
 'Dutch-F': 'Dutch-Colette- (Female)',
 'Dutch-M': 'Dutch-Maarten- (Male)',
 'Norwegian-F': 'Norwegian-Pernille- (Female)',
 'Norwegian-M': 'Norwegian-Finn- (Male)',
 'Swedish-F': 'Swedish-Sofie- (Female)',
 'Swedish-M': 'Swedish-Mattias- (Male)',
 'Arabic-F': 'Arabic-Zariyah- (Female)',
 'Arabic-M': 'Arabic-Hamed- (Male)',
 'Greek-F': 'Greek-Athina- (Female)',
 'Greek-M': 'Greek-Nestoras- (Male)',
 'German-F': 'German-Amala- (Female)',
 'German-M': 'German-Conrad- (Male)',
 'Danish-F': 'Danish (Denmark)-Christel- (Female)',
 'Danish-M': 'Danish (Denmark)-Jeppe- (Male)',
 'Estonian-F': 'Estonian (Estonia)-Anu- (Female)',
 'Estonian-M': 'Estonian (Estonia)-Kert- (Male)',
 'Persian-F': 'Persian (Iran)-Dilara- (Female)',
 'Persian-M': 'Persian (Iran)-Farid- (Male)',
 'Finnish-F': 'Finnish (Finland)-Noora- (Female)',
 'Finnish-M': 'Finnish (Finland)-Harri- (Male)',
}